#!/usr/bin/env node
/**
 * PentestAI PDF Report Generator
 * Generates professional penetration test reports from JSON scan results
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// Color scheme
const colors = {
    primary: '#1a365d',
    secondary: '#2d3748',
    critical: '#c53030',
    high: '#dd6b20',
    medium: '#d69e2e',
    low: '#38a169',
    info: '#3182ce',
    background: '#f7fafc',
    text: '#2d3748',
    lightText: '#718096'
};

// Severity colors
const severityColors = {
    critical: colors.critical,
    high: colors.high,
    medium: colors.medium,
    low: colors.low,
    info: colors.info
};

class PentestReportGenerator {
    constructor(scanData, outputPath) {
        this.scanData = scanData;
        this.outputPath = outputPath;
        this.doc = new PDFDocument({
            size: 'A4',
            margins: { top: 50, bottom: 50, left: 50, right: 50 },
            bufferPages: true
        });
        this.pageNumber = 0;
    }

    generate() {
        const stream = fs.createWriteStream(this.outputPath);
        this.doc.pipe(stream);

        this.addCoverPage();
        this.addExecutiveSummary();
        this.addTestResults();
        this.addVulnerabilities();
        this.addCredentials();
        this.addRecommendations();
        this.addPageNumbers();

        this.doc.end();

        return new Promise((resolve, reject) => {
            stream.on('finish', () => resolve(this.outputPath));
            stream.on('error', reject);
        });
    }

    addCoverPage() {
        const { doc, scanData } = this;

        // Header bar
        doc.rect(0, 0, doc.page.width, 200).fill(colors.primary);

        // Title
        doc.fontSize(36)
           .fillColor('white')
           .text('PENETRATION TEST REPORT', 50, 70, { align: 'center' });

        // Subtitle
        doc.fontSize(16)
           .text('Security Assessment Results', 50, 120, { align: 'center' });

        // Target info box
        doc.rect(50, 250, doc.page.width - 100, 150)
           .fillAndStroke(colors.background, colors.primary);

        doc.fontSize(14)
           .fillColor(colors.primary)
           .text('TARGET INFORMATION', 70, 270);

        doc.fontSize(12)
           .fillColor(colors.text)
           .text(`Target: ${scanData.target || 'N/A'}`, 70, 300)
           .text(`Scan Date: ${scanData.date || new Date().toISOString().split('T')[0]}`, 70, 320)
           .text(`Total Tests: ${scanData.tests?.length || 0}`, 70, 340)
           .text(`Vulnerabilities Found: ${scanData.vulnerabilities?.length || 0}`, 70, 360);

        // Risk summary
        const riskCounts = this.countBySeverity();
        doc.rect(50, 430, doc.page.width - 100, 120)
           .fillAndStroke(colors.background, colors.primary);

        doc.fontSize(14)
           .fillColor(colors.primary)
           .text('RISK SUMMARY', 70, 450);

        let xPos = 70;
        Object.entries(riskCounts).forEach(([severity, count]) => {
            doc.fontSize(24)
               .fillColor(severityColors[severity] || colors.info)
               .text(count.toString(), xPos, 480);
            doc.fontSize(10)
               .fillColor(colors.lightText)
               .text(severity.toUpperCase(), xPos, 510);
            xPos += 90;
        });

        // Footer
        doc.fontSize(10)
           .fillColor(colors.lightText)
           .text('Generated by PentestAI', 50, 750, { align: 'center' })
           .text('CONFIDENTIAL - FOR AUTHORIZED USE ONLY', 50, 765, { align: 'center' });

        doc.addPage();
    }

    addExecutiveSummary() {
        const { doc, scanData } = this;

        this.addSectionHeader('EXECUTIVE SUMMARY');

        const vulnCount = scanData.vulnerabilities?.length || 0;
        const criticalCount = scanData.vulnerabilities?.filter(v => v.severity === 'critical').length || 0;
        const highCount = scanData.vulnerabilities?.filter(v => v.severity === 'high').length || 0;
        const credCount = scanData.credentials?.length || 0;

        doc.fontSize(11)
           .fillColor(colors.text)
           .text(`This penetration test was conducted against ${scanData.target || 'the target system'} ` +
                 `on ${scanData.date || new Date().toISOString().split('T')[0]}. ` +
                 `The assessment identified ${vulnCount} vulnerabilities across multiple security domains.`,
                 50, doc.y + 20, { width: doc.page.width - 100, align: 'justify' });

        if (criticalCount > 0 || highCount > 0) {
            doc.moveDown()
               .fillColor(colors.critical)
               .text(`WARNING: ${criticalCount} critical and ${highCount} high severity vulnerabilities were discovered ` +
                     `that require immediate attention.`, { width: doc.page.width - 100 });
        }

        if (credCount > 0) {
            doc.moveDown()
               .fillColor(colors.high)
               .text(`ALERT: ${credCount} credentials were extracted during testing, indicating serious ` +
                     `authentication or data protection weaknesses.`, { width: doc.page.width - 100 });
        }

        // Key findings
        doc.moveDown(2)
           .fontSize(12)
           .fillColor(colors.primary)
           .text('Key Findings:');

        doc.fontSize(10)
           .fillColor(colors.text);

        const findings = this.generateKeyFindings();
        findings.forEach(finding => {
            doc.moveDown(0.5)
               .text(`• ${finding}`, { width: doc.page.width - 100 });
        });

        doc.addPage();
    }

    addTestResults() {
        const { doc, scanData } = this;

        this.addSectionHeader('TEST RESULTS BY MODULE');

        const tests = scanData.tests || [];

        tests.forEach((test, index) => {
            // Check if we need a new page
            if (doc.y > doc.page.height - 200) {
                doc.addPage();
            }

            // Test card
            const cardY = doc.y + 10;
            const cardHeight = this.calculateTestCardHeight(test);

            // Card background
            doc.rect(50, cardY, doc.page.width - 100, cardHeight)
               .fillAndStroke('#ffffff', colors.secondary);

            // Status indicator
            const statusColor = test.success ? colors.low : colors.medium;
            doc.rect(50, cardY, 5, cardHeight).fill(statusColor);

            // Test name
            doc.fontSize(12)
               .fillColor(colors.primary)
               .text(test.name || test.action || 'Unknown Test', 65, cardY + 10);

            // Target
            doc.fontSize(9)
               .fillColor(colors.lightText)
               .text(`Target: ${test.target || 'N/A'}`, 65, cardY + 28);

            // Status badge
            const statusText = test.success ? 'COMPLETED' : 'FAILED';
            const badgeColor = test.success ? colors.low : colors.medium;
            const badgeX = doc.page.width - 130;
            doc.rect(badgeX, cardY + 8, 70, 18).fill(badgeColor);
            doc.fontSize(8)
               .fillColor('white')
               .text(statusText, badgeX + 5, cardY + 13);

            // Results
            if (test.output || test.results) {
                doc.fontSize(9)
                   .fillColor(colors.text)
                   .text('Results:', 65, cardY + 48);

                const resultText = test.output || test.results || 'No details available';
                const truncated = resultText.length > 300 ? resultText.substring(0, 300) + '...' : resultText;
                doc.fontSize(8)
                   .fillColor(colors.secondary)
                   .text(truncated, 65, cardY + 62, {
                       width: doc.page.width - 140,
                       lineGap: 2
                   });
            }

            // Findings count if any
            const findingsCount = test.findings?.length || 0;
            if (findingsCount > 0) {
                doc.fontSize(9)
                   .fillColor(colors.high)
                   .text(`${findingsCount} finding(s)`, 65, cardY + cardHeight - 20);
            }

            doc.y = cardY + cardHeight + 10;
        });

        doc.addPage();
    }

    addVulnerabilities() {
        const { doc, scanData } = this;

        this.addSectionHeader('VULNERABILITIES');

        const vulns = scanData.vulnerabilities || [];

        if (vulns.length === 0) {
            doc.fontSize(11)
               .fillColor(colors.text)
               .text('No vulnerabilities were identified during this assessment.', 50, doc.y + 20);
            doc.addPage();
            return;
        }

        // Group by severity
        const grouped = this.groupBySeverity(vulns);

        ['critical', 'high', 'medium', 'low', 'info'].forEach(severity => {
            const items = grouped[severity] || [];
            if (items.length === 0) return;

            if (doc.y > doc.page.height - 150) {
                doc.addPage();
            }

            // Severity header
            doc.rect(50, doc.y + 10, doc.page.width - 100, 25)
               .fill(severityColors[severity] || colors.info);
            doc.fontSize(11)
               .fillColor('white')
               .text(`${severity.toUpperCase()} (${items.length})`, 60, doc.y + 17);
            doc.y += 45;

            items.forEach(vuln => {
                if (doc.y > doc.page.height - 100) {
                    doc.addPage();
                }

                doc.fontSize(10)
                   .fillColor(colors.primary)
                   .text(`• ${vuln.type || vuln.name || 'Unknown Vulnerability'}`, 60, doc.y);

                doc.fontSize(9)
                   .fillColor(colors.lightText)
                   .text(`Target: ${vuln.target || 'N/A'}`, 70, doc.y + 15);

                if (vuln.description || vuln.details) {
                    doc.fontSize(9)
                       .fillColor(colors.text)
                       .text(vuln.description || vuln.details, 70, doc.y + 30, {
                           width: doc.page.width - 140
                       });
                }

                doc.y += 55;
            });

            doc.y += 10;
        });

        doc.addPage();
    }

    addCredentials() {
        const { doc, scanData } = this;

        this.addSectionHeader('EXTRACTED CREDENTIALS');

        const creds = scanData.credentials || [];

        if (creds.length === 0) {
            doc.fontSize(11)
               .fillColor(colors.text)
               .text('No credentials were extracted during this assessment.', 50, doc.y + 20);
            doc.addPage();
            return;
        }

        // Warning box
        doc.rect(50, doc.y + 10, doc.page.width - 100, 40)
           .fillAndStroke('#fff5f5', colors.critical);
        doc.fontSize(10)
           .fillColor(colors.critical)
           .text('SENSITIVE DATA - The following credentials were extracted during testing. ' +
                 'Immediate password resets are recommended.', 60, doc.y + 22, { width: doc.page.width - 120 });
        doc.y += 60;

        // Credentials table header
        const tableTop = doc.y + 10;
        doc.rect(50, tableTop, doc.page.width - 100, 25).fill(colors.secondary);
        doc.fontSize(10)
           .fillColor('white')
           .text('Username', 60, tableTop + 8)
           .text('Password/Hash', 180, tableTop + 8)
           .text('Source', 350, tableTop + 8)
           .text('Type', 480, tableTop + 8);

        doc.y = tableTop + 25;

        // Credentials rows
        creds.forEach((cred, index) => {
            if (doc.y > doc.page.height - 50) {
                doc.addPage();
            }

            const rowY = doc.y;
            const bgColor = index % 2 === 0 ? '#ffffff' : colors.background;
            doc.rect(50, rowY, doc.page.width - 100, 22).fill(bgColor);

            doc.fontSize(9)
               .fillColor(colors.text)
               .text(cred.username || 'N/A', 60, rowY + 6)
               .text(this.maskPassword(cred.password || cred.hash || 'N/A'), 180, rowY + 6)
               .text(cred.source || cred.service || 'N/A', 350, rowY + 6)
               .text(cred.type || 'password', 480, rowY + 6);

            doc.y = rowY + 22;
        });

        doc.addPage();
    }

    addRecommendations() {
        const { doc, scanData } = this;

        this.addSectionHeader('RECOMMENDATIONS');

        const recommendations = this.generateRecommendations();

        doc.fontSize(11)
           .fillColor(colors.text)
           .text('Based on the findings of this assessment, the following remediation actions are recommended:',
                 50, doc.y + 20, { width: doc.page.width - 100 });

        doc.y += 50;

        recommendations.forEach((rec, index) => {
            if (doc.y > doc.page.height - 100) {
                doc.addPage();
            }

            // Priority badge
            const priorityColors = { 'Critical': colors.critical, 'High': colors.high, 'Medium': colors.medium, 'Low': colors.low };
            doc.rect(50, doc.y, 60, 20).fill(priorityColors[rec.priority] || colors.info);
            doc.fontSize(8)
               .fillColor('white')
               .text(rec.priority, 55, doc.y + 6);

            // Recommendation text
            doc.fontSize(10)
               .fillColor(colors.primary)
               .text(rec.title, 120, doc.y + 3);

            doc.fontSize(9)
               .fillColor(colors.text)
               .text(rec.description, 50, doc.y + 28, { width: doc.page.width - 100 });

            doc.y += 70;
        });
    }

    addSectionHeader(title) {
        const { doc } = this;

        doc.rect(0, doc.y, doc.page.width, 40).fill(colors.primary);
        doc.fontSize(16)
           .fillColor('white')
           .text(title, 50, doc.y + 12);
        doc.y += 50;
    }

    addPageNumbers() {
        const { doc } = this;
        const pages = doc.bufferedPageRange();

        for (let i = 0; i < pages.count; i++) {
            doc.switchToPage(i);
            doc.fontSize(8)
               .fillColor(colors.lightText)
               .text(`Page ${i + 1} of ${pages.count}`,
                     50, doc.page.height - 30,
                     { align: 'center', width: doc.page.width - 100 });
        }
    }

    calculateTestCardHeight(test) {
        let height = 80;
        if (test.output || test.results) {
            const textLength = (test.output || test.results || '').length;
            height += Math.min(Math.ceil(textLength / 80) * 12, 60);
        }
        if (test.findings?.length > 0) height += 20;
        return height;
    }

    countBySeverity() {
        const vulns = this.scanData.vulnerabilities || [];
        return {
            critical: vulns.filter(v => v.severity === 'critical').length,
            high: vulns.filter(v => v.severity === 'high').length,
            medium: vulns.filter(v => v.severity === 'medium').length,
            low: vulns.filter(v => v.severity === 'low').length,
            info: vulns.filter(v => v.severity === 'info').length
        };
    }

    groupBySeverity(vulns) {
        return vulns.reduce((acc, vuln) => {
            const sev = vuln.severity || 'info';
            if (!acc[sev]) acc[sev] = [];
            acc[sev].push(vuln);
            return acc;
        }, {});
    }

    maskPassword(password) {
        if (!password || password === 'N/A') return 'N/A';
        if (password.length <= 4) return '****';
        return password.substring(0, 2) + '****' + password.substring(password.length - 2);
    }

    generateKeyFindings() {
        const findings = [];
        const { scanData } = this;

        const criticalCount = scanData.vulnerabilities?.filter(v => v.severity === 'critical').length || 0;
        if (criticalCount > 0) {
            findings.push(`${criticalCount} critical vulnerabilities require immediate remediation`);
        }

        const credCount = scanData.credentials?.length || 0;
        if (credCount > 0) {
            findings.push(`${credCount} user credentials were extracted via SQL injection or other attacks`);
        }

        const headerIssues = scanData.vulnerabilities?.filter(v =>
            v.type?.includes('header') || v.name?.includes('header')).length || 0;
        if (headerIssues > 0) {
            findings.push(`${headerIssues} security header misconfigurations detected`);
        }

        const sslIssues = scanData.vulnerabilities?.filter(v =>
            v.type?.includes('ssl') || v.type?.includes('tls')).length || 0;
        if (sslIssues > 0) {
            findings.push(`SSL/TLS configuration issues identified`);
        }

        if (findings.length === 0) {
            findings.push('No critical security issues were identified');
        }

        return findings;
    }

    generateRecommendations() {
        const recommendations = [];
        const { scanData } = this;

        const criticalVulns = scanData.vulnerabilities?.filter(v => v.severity === 'critical') || [];
        if (criticalVulns.length > 0) {
            recommendations.push({
                priority: 'Critical',
                title: 'Address Critical Vulnerabilities',
                description: 'Immediately patch or mitigate all critical vulnerabilities including SQL injection, ' +
                            'remote code execution, and authentication bypass issues.'
            });
        }

        if (scanData.credentials?.length > 0) {
            recommendations.push({
                priority: 'Critical',
                title: 'Reset Compromised Credentials',
                description: 'Force password resets for all extracted credentials. Implement strong password ' +
                            'policies and consider multi-factor authentication.'
            });
        }

        const headerIssues = scanData.vulnerabilities?.filter(v =>
            v.type?.includes('header')).length || 0;
        if (headerIssues > 0) {
            recommendations.push({
                priority: 'Medium',
                title: 'Implement Security Headers',
                description: 'Configure proper security headers including X-Frame-Options, Content-Security-Policy, ' +
                            'X-XSS-Protection, X-Content-Type-Options, and HSTS.'
            });
        }

        recommendations.push({
            priority: 'Medium',
            title: 'Regular Security Assessments',
            description: 'Conduct regular penetration tests and vulnerability assessments to identify and ' +
                        'address security issues before they can be exploited.'
        });

        recommendations.push({
            priority: 'Low',
            title: 'Security Awareness Training',
            description: 'Provide ongoing security awareness training to development and operations teams ' +
                        'to prevent introduction of new vulnerabilities.'
        });

        return recommendations;
    }
}

// Main execution
async function main() {
    const args = process.argv.slice(2);

    if (args.length < 1) {
        console.log('Usage: node generate-report.js <scan-results.json> [output.pdf]');
        console.log('\nExample JSON structure:');
        console.log(JSON.stringify({
            target: 'example.com',
            date: '2025-12-10',
            tests: [
                { name: 'Port Scan', action: 'full_scan', target: 'example.com', success: true, output: '3 ports found' }
            ],
            vulnerabilities: [
                { type: 'sql_injection', severity: 'critical', target: 'http://example.com', description: 'SQL injection found' }
            ],
            credentials: [
                { username: 'admin', password: 'password123', source: 'sqli_dump', type: 'password' }
            ]
        }, null, 2));
        process.exit(1);
    }

    const inputFile = args[0];
    const outputFile = args[1] || inputFile.replace('.json', '') + '-report.pdf';

    try {
        console.log(`Reading scan results from: ${inputFile}`);
        const scanData = JSON.parse(fs.readFileSync(inputFile, 'utf8'));

        console.log(`Generating PDF report: ${outputFile}`);
        const generator = new PentestReportGenerator(scanData, outputFile);
        await generator.generate();

        console.log(`\nReport generated successfully: ${outputFile}`);
    } catch (error) {
        console.error('Error generating report:', error.message);
        process.exit(1);
    }
}

main();
