package remediation

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// FixMode determines how aggressive the autofix should be
type FixMode int

const (
	// FixModeSafe only applies fixes that cannot break functionality
	FixModeSafe FixMode = iota
	// FixModeReview generates patches for human review
	FixModeReview
)

// Fix represents a single remediation fix
type Fix struct {
	VulnType    string   `json:"vuln_type"`
	Target      string   `json:"target"`
	Description string   `json:"description"`
	FixType     string   `json:"fix_type"` // "config", "code", "docker", "firewall"
	Safe        bool     `json:"safe"`     // Can be auto-applied without breaking things
	Applied     bool     `json:"applied"`
	FilePath    string   `json:"file_path,omitempty"`
	Original    string   `json:"original,omitempty"`
	Patched     string   `json:"patched,omitempty"`
	Commands    []string `json:"commands,omitempty"` // Commands to run
	Error       string   `json:"error,omitempty"`
}

// FixResult contains the results of an autofix operation
type FixResult struct {
	Mode         FixMode   `json:"mode"`
	TotalVulns   int       `json:"total_vulns"`
	FixesApplied int       `json:"fixes_applied"`
	FixesPending int       `json:"fixes_pending"`
	Fixes        []*Fix    `json:"fixes"`
	StartTime    time.Time `json:"start_time"`
	EndTime      time.Time `json:"end_time"`
}

// AutoFixer handles automatic remediation
type AutoFixer struct {
	db        *Database
	mode      FixMode
	outputDir string
	fixes     []*Fix
	dryRun    bool
}

// NewAutoFixer creates a new auto-fixer
func NewAutoFixer(mode FixMode, outputDir string) *AutoFixer {
	return &AutoFixer{
		db:        NewDatabase(),
		mode:      mode,
		outputDir: outputDir,
		fixes:     make([]*Fix, 0),
		dryRun:    false,
	}
}

// SetDryRun enables dry-run mode (generate but don't apply)
func (af *AutoFixer) SetDryRun(dryRun bool) {
	af.dryRun = dryRun
}

// GenerateFixes analyzes vulnerabilities and generates fixes
func (af *AutoFixer) GenerateFixes(vulns []VulnInput) *FixResult {
	result := &FixResult{
		Mode:      af.mode,
		StartTime: time.Now(),
		Fixes:     make([]*Fix, 0),
	}

	for _, vuln := range vulns {
		fixes := af.generateFixesForVuln(vuln)
		result.Fixes = append(result.Fixes, fixes...)
	}

	result.TotalVulns = len(vulns)
	result.EndTime = time.Now()

	// Count applied vs pending
	for _, fix := range result.Fixes {
		if fix.Applied {
			result.FixesApplied++
		} else {
			result.FixesPending++
		}
	}

	return result
}

// VulnInput represents a vulnerability to fix
type VulnInput struct {
	Type        string `json:"type"`
	Target      string `json:"target"`
	Service     string `json:"service"`
	Description string `json:"description"`
	Evidence    string `json:"evidence"`
}

// generateFixesForVuln creates fixes for a single vulnerability
func (af *AutoFixer) generateFixesForVuln(vuln VulnInput) []*Fix {
	var fixes []*Fix

	switch {
	case strings.Contains(vuln.Type, "security_header") || strings.Contains(vuln.Type, "missing_header"):
		fixes = append(fixes, af.fixSecurityHeaders(vuln)...)
	case strings.Contains(vuln.Type, "redis_unauth"):
		fixes = append(fixes, af.fixRedisUnauth(vuln))
	case strings.Contains(vuln.Type, "mongodb_unauth"):
		fixes = append(fixes, af.fixMongoDBUnauth(vuln))
	case strings.Contains(vuln.Type, "ssh"):
		fixes = append(fixes, af.fixSSH(vuln))
	case strings.Contains(vuln.Type, "rpc_command_injection") || strings.Contains(vuln.Type, "command_injection"):
		fixes = append(fixes, af.fixCommandInjection(vuln))
	case strings.Contains(vuln.Type, "grpc"):
		fixes = append(fixes, af.fixGRPC(vuln))
	case strings.Contains(vuln.Type, "sql"):
		fixes = append(fixes, af.fixSQLInjection(vuln))
	case strings.Contains(vuln.Type, "info_disclosure"):
		fixes = append(fixes, af.fixInfoDisclosure(vuln))
	case strings.Contains(vuln.Type, "ftp_anonymous"):
		fixes = append(fixes, af.fixFTPAnonymous(vuln))
	case strings.Contains(vuln.Type, "default_credentials"):
		fixes = append(fixes, af.fixDefaultCredentials(vuln))
	}

	return fixes
}

// fixSecurityHeaders generates fixes for missing security headers
func (af *AutoFixer) fixSecurityHeaders(vuln VulnInput) []*Fix {
	var fixes []*Fix

	// This is SAFE - adding headers doesn't break functionality
	nginxConfig := `# Security Headers - Auto-generated by PentestAI
add_header X-Content-Type-Options "nosniff" always;
add_header X-Frame-Options "DENY" always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
`

	apacheConfig := `# Security Headers - Auto-generated by PentestAI
Header always set X-Content-Type-Options "nosniff"
Header always set X-Frame-Options "DENY"
Header always set X-XSS-Protection "1; mode=block"
Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
Header always set Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'"
Header always set Referrer-Policy "strict-origin-when-cross-origin"
`

	fix := &Fix{
		VulnType:    vuln.Type,
		Target:      vuln.Target,
		Description: "Add missing security headers to web server",
		FixType:     "config",
		Safe:        true, // Headers don't break functionality
		FilePath:    filepath.Join(af.outputDir, "patches", "security-headers-nginx.conf"),
		Patched:     nginxConfig,
	}

	if af.mode == FixModeSafe && !af.dryRun {
		if err := af.writePatchFile(fix.FilePath, nginxConfig); err != nil {
			fix.Error = err.Error()
		} else {
			fix.Applied = true
		}
	}
	fixes = append(fixes, fix)

	// Also generate Apache version
	apacheFix := &Fix{
		VulnType:    vuln.Type,
		Target:      vuln.Target,
		Description: "Add missing security headers (Apache version)",
		FixType:     "config",
		Safe:        true,
		FilePath:    filepath.Join(af.outputDir, "patches", "security-headers-apache.conf"),
		Patched:     apacheConfig,
	}

	if af.mode == FixModeSafe && !af.dryRun {
		if err := af.writePatchFile(apacheFix.FilePath, apacheConfig); err != nil {
			apacheFix.Error = err.Error()
		} else {
			apacheFix.Applied = true
		}
	}
	fixes = append(fixes, apacheFix)

	return fixes
}

// fixRedisUnauth generates fix for unauthenticated Redis
func (af *AutoFixer) fixRedisUnauth(vuln VulnInput) *Fix {
	redisConfig := `# Redis Security Configuration - Auto-generated by PentestAI
# IMPORTANT: Change the password below!
bind 127.0.0.1
protected-mode yes
requirepass CHANGE_THIS_TO_A_STRONG_PASSWORD

# Disable dangerous commands
rename-command CONFIG ""
rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command DEBUG ""
rename-command SHUTDOWN ""
`

	fix := &Fix{
		VulnType:    vuln.Type,
		Target:      vuln.Target,
		Description: "Secure Redis with authentication and bind to localhost",
		FixType:     "config",
		Safe:        true, // Auto-apply - unauthenticated Redis is critical
		FilePath:    filepath.Join(af.outputDir, "patches", "redis-secure.conf"),
		Patched:     redisConfig,
		Commands: []string{
			"# Apply with: sudo cp redis-secure.conf /etc/redis/redis.conf && sudo systemctl restart redis",
		},
	}

	if af.mode == FixModeSafe && !af.dryRun {
		if err := af.writePatchFile(fix.FilePath, redisConfig); err != nil {
			fix.Error = err.Error()
		} else {
			fix.Applied = true
		}
	} else if !af.dryRun {
		af.writePatchFile(fix.FilePath, redisConfig)
	}

	return fix
}

// fixMongoDBUnauth generates fix for unauthenticated MongoDB
func (af *AutoFixer) fixMongoDBUnauth(vuln VulnInput) *Fix {
	mongoConfig := `# MongoDB Security Configuration - Auto-generated by PentestAI
security:
  authorization: enabled

net:
  bindIp: 127.0.0.1
  port: 27017

# Create admin user with:
# use admin
# db.createUser({user: "admin", pwd: "CHANGE_THIS", roles: ["root"]})
`

	fix := &Fix{
		VulnType:    vuln.Type,
		Target:      vuln.Target,
		Description: "Enable MongoDB authentication and bind to localhost",
		FixType:     "config",
		Safe:        true, // Auto-apply - unauthenticated MongoDB is critical
		FilePath:    filepath.Join(af.outputDir, "patches", "mongod-secure.conf"),
		Patched:     mongoConfig,
		Commands: []string{
			"# 1. Create admin user first (while auth is disabled)",
			"# 2. Apply config: sudo cp mongod-secure.conf /etc/mongod.conf",
			"# 3. Restart: sudo systemctl restart mongod",
		},
	}

	if af.mode == FixModeSafe && !af.dryRun {
		if err := af.writePatchFile(fix.FilePath, mongoConfig); err != nil {
			fix.Error = err.Error()
		} else {
			fix.Applied = true
		}
	} else if !af.dryRun {
		af.writePatchFile(fix.FilePath, mongoConfig)
	}

	return fix
}

// fixSSH generates SSH hardening configuration
func (af *AutoFixer) fixSSH(vuln VulnInput) *Fix {
	sshdConfig := `# SSH Hardening Configuration - Auto-generated by PentestAI
# REVIEW BEFORE APPLYING - ensure you have key-based access first!

Protocol 2
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# Limit users (uncomment and modify)
# AllowUsers admin deployer

# Strong crypto
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

# Timeouts
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 60
MaxAuthTries 3

# Logging
LogLevel VERBOSE
`

	fix := &Fix{
		VulnType:    vuln.Type,
		Target:      vuln.Target,
		Description: "Harden SSH configuration - disable password auth, use keys only",
		FixType:     "config",
		Safe:        false, // Could lock out users - needs careful review!
		FilePath:    filepath.Join(af.outputDir, "patches", "sshd_config-hardened"),
		Patched:     sshdConfig,
		Commands: []string{
			"# WARNING: Ensure you have key-based access before applying!",
			"# 1. Generate SSH key: ssh-keygen -t ed25519",
			"# 2. Copy to server: ssh-copy-id user@server",
			"# 3. Test key login works",
			"# 4. Then apply: sudo cp sshd_config-hardened /etc/ssh/sshd_config",
			"# 5. Restart: sudo systemctl restart sshd",
		},
	}

	if !af.dryRun {
		af.writePatchFile(fix.FilePath, sshdConfig)
	}

	return fix
}

// fixCommandInjection generates fix for command injection (RPC services)
func (af *AutoFixer) fixCommandInjection(vuln VulnInput) *Fix {
	var patchContent string
	var description string

	if strings.Contains(vuln.Service, "xmlrpc") || strings.Contains(vuln.Target, "8086") {
		patchContent = `# XML-RPC Security Fix - Auto-generated by PentestAI
# Replace dangerous execute function with safe version

# OPTION 1: Remove dangerous methods entirely (recommended)
# Remove: server.register_function(execute, "system.execute")

# OPTION 2: If execute is needed, use allowlist
ALLOWED_COMMANDS = ['status', 'health', 'version', 'ping']

def safe_execute(cmd):
    """Secure command execution with allowlist"""
    if cmd not in ALLOWED_COMMANDS:
        raise ValueError(f"Command '{cmd}' not allowed. Allowed: {ALLOWED_COMMANDS}")
    # Only run pre-approved commands
    if cmd == 'status':
        return {'status': 'ok', 'uptime': get_uptime()}
    elif cmd == 'health':
        return {'health': 'healthy'}
    elif cmd == 'version':
        return {'version': '1.0.0'}
    elif cmd == 'ping':
        return {'pong': True}

# OPTION 3: If dynamic commands needed, use strict validation
import shlex
import subprocess

def validated_execute(cmd):
    """Execute with input validation - still risky!"""
    # Allowlist of safe binaries only
    SAFE_BINARIES = ['/usr/bin/date', '/usr/bin/uptime', '/usr/bin/hostname']

    parts = shlex.split(cmd)
    if not parts or parts[0] not in SAFE_BINARIES:
        raise ValueError("Command not in allowlist")

    # Use list form, NOT shell=True
    result = subprocess.run(parts, capture_output=True, text=True, timeout=5)
    return result.stdout
`
		description = "Remove or secure XML-RPC system.execute method"
	} else if strings.Contains(vuln.Service, "grpc") || strings.Contains(vuln.Target, "50051") {
		patchContent = `# gRPC Security Fix - Auto-generated by PentestAI
# The current gRPC service executes raw commands - this is critical!

# OPTION 1: Add authentication (recommended)
import grpc

def create_secure_server():
    # Load TLS credentials
    with open('server.key', 'rb') as f:
        private_key = f.read()
    with open('server.crt', 'rb') as f:
        certificate_chain = f.read()

    credentials = grpc.ssl_server_credentials([(private_key, certificate_chain)])
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    server.add_secure_port('[::]:50051', credentials)
    return server

# OPTION 2: Add API key authentication
def authenticate(func):
    def wrapper(request, context):
        metadata = dict(context.invocation_metadata())
        api_key = metadata.get('x-api-key')
        if api_key != os.environ.get('GRPC_API_KEY'):
            context.abort(grpc.StatusCode.UNAUTHENTICATED, 'Invalid API key')
        return func(request, context)
    return wrapper

# OPTION 3: Remove command execution entirely
# Replace direct command execution with specific, safe operations only
class SafeService(ServiceServicer):
    def GetStatus(self, request, context):
        return StatusResponse(status='ok', uptime=get_uptime())

    def GetHealth(self, request, context):
        return HealthResponse(healthy=True)

    # NO execute method!
`
		description = "Secure gRPC service - add authentication, remove command execution"
	} else {
		patchContent = `# Command Injection Fix - Auto-generated by PentestAI
# Generic guidance for securing command execution

# NEVER DO THIS:
# os.system(user_input)
# subprocess.run(user_input, shell=True)
# exec(user_input)
# eval(user_input)

# INSTEAD:
# 1. Avoid shell commands entirely - use language-native functions
# 2. If you must use commands, use allowlists
# 3. Use subprocess with list arguments, NOT shell=True
# 4. Validate and sanitize all input

import subprocess
import re

def safe_ping(host):
    """Example: Safe ping implementation"""
    # Validate input is an IP address
    if not re.match(r'^(\d{1,3}\.){3}\d{1,3}$', host):
        raise ValueError("Invalid IP address format")

    # Use list form - no shell injection possible
    result = subprocess.run(
        ['ping', '-c', '1', '-W', '2', host],
        capture_output=True,
        text=True,
        timeout=5
    )
    return result.stdout
`
		description = "Secure command execution - use allowlists and subprocess list form"
	}

	fix := &Fix{
		VulnType:    vuln.Type,
		Target:      vuln.Target,
		Description: description,
		FixType:     "code",
		Safe:        true, // Auto-apply - these are critical RCE vulns that must be fixed
		FilePath:    filepath.Join(af.outputDir, "patches", "command-injection-fix.py"),
		Patched:     patchContent,
	}

	if af.mode == FixModeSafe && !af.dryRun {
		if err := af.writePatchFile(fix.FilePath, patchContent); err != nil {
			fix.Error = err.Error()
		} else {
			fix.Applied = true
		}
	} else if !af.dryRun {
		af.writePatchFile(fix.FilePath, patchContent)
	}

	return fix
}

// fixGRPC generates gRPC-specific security fixes
func (af *AutoFixer) fixGRPC(vuln VulnInput) *Fix {
	return af.fixCommandInjection(VulnInput{
		Type:    vuln.Type,
		Target:  vuln.Target,
		Service: "grpc",
	})
}

// fixSQLInjection generates SQL injection fix
func (af *AutoFixer) fixSQLInjection(vuln VulnInput) *Fix {
	patchContent := `# SQL Injection Fix - Auto-generated by PentestAI

# VULNERABLE (never do this):
# query = "SELECT * FROM users WHERE id = " + user_id
# cursor.execute(query)

# SECURE (use parameterized queries):

# Python with psycopg2 (PostgreSQL)
def get_user_secure(user_id):
    query = "SELECT * FROM users WHERE id = %s"
    cursor.execute(query, (user_id,))
    return cursor.fetchone()

# Python with sqlite3
def get_user_sqlite(user_id):
    query = "SELECT * FROM users WHERE id = ?"
    cursor.execute(query, (user_id,))
    return cursor.fetchone()

# Python with SQLAlchemy ORM (recommended)
def get_user_orm(user_id):
    return session.query(User).filter(User.id == user_id).first()

# Node.js with prepared statements
# const query = 'SELECT * FROM users WHERE id = $1';
# const result = await pool.query(query, [userId]);

# Go with database/sql
# query := "SELECT * FROM users WHERE id = $1"
# row := db.QueryRow(query, userID)
`

	fix := &Fix{
		VulnType:    vuln.Type,
		Target:      vuln.Target,
		Description: "Replace dynamic SQL with parameterized queries",
		FixType:     "code",
		Safe:        false, // Code changes need review
		FilePath:    filepath.Join(af.outputDir, "patches", "sql-injection-fix.py"),
		Patched:     patchContent,
	}

	if !af.dryRun {
		af.writePatchFile(fix.FilePath, patchContent)
	}

	return fix
}

// fixInfoDisclosure generates info disclosure fix
func (af *AutoFixer) fixInfoDisclosure(vuln VulnInput) *Fix {
	nginxConfig := `# Hide Server Information - Auto-generated by PentestAI

# In http block:
server_tokens off;

# Remove Server header entirely (requires headers-more module):
# more_clear_headers Server;

# Or set custom value:
# more_set_headers 'Server: ';
`

	fix := &Fix{
		VulnType:    vuln.Type,
		Target:      vuln.Target,
		Description: "Hide server version and technology information",
		FixType:     "config",
		Safe:        true, // Hiding version info is safe
		FilePath:    filepath.Join(af.outputDir, "patches", "hide-server-info.conf"),
		Patched:     nginxConfig,
	}

	if af.mode == FixModeSafe && !af.dryRun {
		if err := af.writePatchFile(fix.FilePath, nginxConfig); err != nil {
			fix.Error = err.Error()
		} else {
			fix.Applied = true
		}
	}

	return fix
}

// fixFTPAnonymous generates FTP anonymous access fix
func (af *AutoFixer) fixFTPAnonymous(vuln VulnInput) *Fix {
	vsftpdConfig := `# vsftpd Security Configuration - Auto-generated by PentestAI

# Disable anonymous access
anonymous_enable=NO
local_enable=YES
write_enable=YES

# Chroot users to their home directory
chroot_local_user=YES
allow_writeable_chroot=YES

# Enable SSL/TLS
ssl_enable=YES
force_local_data_ssl=YES
force_local_logins_ssl=YES
ssl_tlsv1=YES
ssl_sslv2=NO
ssl_sslv3=NO

# Passive mode settings (adjust for your firewall)
pasv_enable=YES
pasv_min_port=40000
pasv_max_port=40100

# Logging
xferlog_enable=YES
xferlog_std_format=NO
log_ftp_protocol=YES
`

	fix := &Fix{
		VulnType:    vuln.Type,
		Target:      vuln.Target,
		Description: "Disable FTP anonymous access, enable SSL",
		FixType:     "config",
		Safe:        true, // Auto-apply - anonymous FTP is a security risk
		FilePath:    filepath.Join(af.outputDir, "patches", "vsftpd-secure.conf"),
		Patched:     vsftpdConfig,
		Commands: []string{
			"# Apply with: sudo cp vsftpd-secure.conf /etc/vsftpd.conf",
			"# Restart: sudo systemctl restart vsftpd",
		},
	}

	if af.mode == FixModeSafe && !af.dryRun {
		if err := af.writePatchFile(fix.FilePath, vsftpdConfig); err != nil {
			fix.Error = err.Error()
		} else {
			fix.Applied = true
		}
	} else if !af.dryRun {
		af.writePatchFile(fix.FilePath, vsftpdConfig)
	}

	return fix
}

// fixDefaultCredentials generates credential change guidance
func (af *AutoFixer) fixDefaultCredentials(vuln VulnInput) *Fix {
	guidance := fmt.Sprintf(`# Default Credentials Fix - Auto-generated by PentestAI
# Target: %s

# IMMEDIATE ACTION REQUIRED:
# 1. Change the default password immediately
# 2. Use a strong password (min 16 chars, mixed case, numbers, symbols)
# 3. Consider using a password manager

# Generate strong password:
# openssl rand -base64 24

# For SSH, switch to key-based auth:
# ssh-keygen -t ed25519 -C "your_email@example.com"
# ssh-copy-id user@server

# For databases, create new users with limited privileges:
# CREATE USER 'appuser'@'localhost' IDENTIFIED BY 'STRONG_PASSWORD_HERE';
# GRANT SELECT, INSERT, UPDATE ON mydb.* TO 'appuser'@'localhost';

# For web apps, use environment variables for credentials:
# export DB_PASSWORD="$(openssl rand -base64 24)"
`, vuln.Target)

	fix := &Fix{
		VulnType:    vuln.Type,
		Target:      vuln.Target,
		Description: "Change default credentials to strong, unique passwords",
		FixType:     "manual",
		Safe:        false, // Requires human to change passwords
		FilePath:    filepath.Join(af.outputDir, "patches", "credential-change-guide.txt"),
		Patched:     guidance,
	}

	if !af.dryRun {
		af.writePatchFile(fix.FilePath, guidance)
	}

	return fix
}

// writePatchFile writes a patch file to disk
func (af *AutoFixer) writePatchFile(path, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0644)
}

// GenerateReport creates a human-readable fix report
func (af *AutoFixer) GenerateReport(result *FixResult) string {
	var sb strings.Builder

	sb.WriteString("╔══════════════════════════════════════════════════════════════╗\n")
	sb.WriteString("║              AUTOFIX REMEDIATION REPORT                      ║\n")
	sb.WriteString("╚══════════════════════════════════════════════════════════════╝\n\n")

	sb.WriteString(fmt.Sprintf("Mode: %s\n", modeToString(result.Mode)))
	sb.WriteString(fmt.Sprintf("Generated: %s\n\n", result.EndTime.Format("2006-01-02 15:04:05")))

	sb.WriteString("═══ SUMMARY ═══\n")
	sb.WriteString(fmt.Sprintf("Total Vulnerabilities: %d\n", result.TotalVulns))
	sb.WriteString(fmt.Sprintf("Fixes Generated: %d\n", len(result.Fixes)))
	sb.WriteString(fmt.Sprintf("Auto-Applied (Safe): %d\n", result.FixesApplied))
	sb.WriteString(fmt.Sprintf("Pending Review: %d\n\n", result.FixesPending))

	// Group by safe/review needed
	var safeFixes, reviewFixes []*Fix
	for _, fix := range result.Fixes {
		if fix.Safe {
			safeFixes = append(safeFixes, fix)
		} else {
			reviewFixes = append(reviewFixes, fix)
		}
	}

	if len(safeFixes) > 0 {
		sb.WriteString("═══ SAFE FIXES (Auto-Applied) ═══\n")
		for _, fix := range safeFixes {
			status := "✓ APPLIED"
			if fix.Error != "" {
				status = "✗ ERROR: " + fix.Error
			} else if !fix.Applied {
				status = "○ GENERATED"
			}
			sb.WriteString(fmt.Sprintf("\n[%s] %s\n", status, fix.Description))
			sb.WriteString(fmt.Sprintf("   Target: %s\n", fix.Target))
			sb.WriteString(fmt.Sprintf("   File: %s\n", fix.FilePath))
		}
		sb.WriteString("\n")
	}

	if len(reviewFixes) > 0 {
		sb.WriteString("═══ FIXES REQUIRING REVIEW ═══\n")
		sb.WriteString("These fixes could break functionality - review before applying!\n")
		for _, fix := range reviewFixes {
			sb.WriteString(fmt.Sprintf("\n[REVIEW] %s\n", fix.Description))
			sb.WriteString(fmt.Sprintf("   Target: %s\n", fix.Target))
			sb.WriteString(fmt.Sprintf("   Type: %s\n", fix.FixType))
			sb.WriteString(fmt.Sprintf("   File: %s\n", fix.FilePath))
			if len(fix.Commands) > 0 {
				sb.WriteString("   Apply with:\n")
				for _, cmd := range fix.Commands {
					sb.WriteString(fmt.Sprintf("     %s\n", cmd))
				}
			}
		}
		sb.WriteString("\n")
	}

	sb.WriteString("═══ NEXT STEPS ═══\n")
	sb.WriteString("1. Review all generated patches in: " + af.outputDir + "/patches/\n")
	sb.WriteString("2. Test patches in a staging environment first\n")
	sb.WriteString("3. Apply safe fixes to production\n")
	sb.WriteString("4. Schedule maintenance window for review-required fixes\n")
	sb.WriteString("5. Re-run autopwn to verify fixes\n")

	return sb.String()
}

func modeToString(mode FixMode) string {
	switch mode {
	case FixModeSafe:
		return "SAFE (auto-apply non-breaking fixes)"
	case FixModeReview:
		return "REVIEW (generate all fixes for human review)"
	default:
		return "UNKNOWN"
	}
}
